spring:
  application:
    name: hodei-notifications

logging:
  level:
    root: info
    io.swagger.v3.oas: trace
    com.github.labcabrera: trace

app:
  mongodb:
    commons:
      uri: mongodb://cnp-mongo
      database: hodei-commons
    customers:
      uri: mongodb://cnp-mongo
      database: hodei-customers
      
  security:
    jwt:
      secret: ${APP_JWT_SECRET:changeit}
      expiration: 18000
      alternate-header: X-Authorization
    authentication:
      enabled: false
      path: /token
    authorization:
      enabled: true
    unsecured:
      paths: >-
        /,
        /v3/api-docs,
        /v3/api-docs/**,
        /swagger-ui/**,
        /swagger-ui.html,
        /swagger-resources/**,
        /webjars/**,
        /actuator,
        /actuator/**
