spring:
  application:
    name: hodei-customers-api
    
  cloud:
    stream:
      bindings:
        sendNotification:
          destination: hodei-notifications

  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: info
    com.github.labcabrera: trace

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: http://some.domain.com
     # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION

app:
  demo: true
  mongodb:
    commons:
      uri: mongodb://cnp-mongo
      database: hodei-commons
    customers:
      uri: mongodb://cnp-mongo
      database: hodei-customers
      
  security:
    jwt:
      secret: ${APP_JWT_SECRET:changeit}
      expiration: 18000
      alternate-header: X-Authorization
    authentication:
      enabled: false
      path: /token
    authorization:
      enabled: true
    unsecured:
      paths: >-
        /,
        /v3/api-docs,
        /v3/api-docs/**,
        /swagger-ui/**,
        /swagger-ui.html,
        /swagger-resources/**,
        /webjars/**,
        /actuator,
        /actuator/**,
        /graphql,
        /graphql/**,
        /graphiql,
        /graphiql/**,
        /vendor/**,
        /subscriptions
